zookeeper:
  image: confluent/zookeeper
  hostname: zookeeper
  ports:
    - "2181:2181"

kafka:
  image: confluent/kafka
  hostname: kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper:zookeeper
  environment:
    KAFKA_ADVERTISED_HOST_NAME: kafka
    KAFKA_ADVERTISED_PORT: 9092

schemaregistry:
  image: confluent/schema-registry
  hostname: schema-registry
  ports:
    - "8081:8081"
  links:
    - zookeeper:zookeeper
    - kafka:kafka

producer:
  image: agentoo7/bitcoin-transaction-producer
  #build: ../bitcoin-transaction-producer
  hostname: producer
  links:
    - zookeeper:zookeeper
    - kafka:kafka
  environment:
    ZOOKEEPER_HOSTNAME: zookeeper

# Keep below as a backup to see that the direct Kafka to Spark Streaming connection is indeed running
spark:
  image: gettyimages/spark
  hostname: spark
  command: run-example streaming.DirectKafkaWordCount kafka:9092 transactions
  links:
    - kafka:kafka

sparknotebook:
  image: andypetrella/spark-notebook:0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.7.1-with-hive-with-parquet
  hostname: spark-notebook
  ports:
    - "9000:9000"
  links:
    - kafka:kafka
